"""Create orders table

Revision ID: 48137902521e
Revises: fc19dc4a462b
Create Date: 2026-02-14 01:25:40.510222

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "48137902521e"
down_revision: Union[str, Sequence[str], None] = "fc19dc4a462b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
