"""Create orders table

Revision ID: 9bb30ddc5708
Revises:
Create Date: 2026-02-09 15:31:42.271675

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "9bb30ddc5708"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
