"""Create orders table

Revision ID: b4f63a3b0228
Revises: e916d7a84249
Create Date: 2026-02-14 16:11:00.364209

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "b4f63a3b0228"
down_revision: Union[str, Sequence[str], None] = "e916d7a84249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
