"""Create orders table

Revision ID: d681f98805da
Revises: 30b1994a4582
Create Date: 2026-02-14 01:31:44.991300

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "d681f98805da"
down_revision: Union[str, Sequence[str], None] = "30b1994a4582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
