"""Create orders table

Revision ID: e916d7a84249
Revises: be8edcbbc16f
Create Date: 2026-02-14 15:59:14.877939

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "e916d7a84249"
down_revision: Union[str, Sequence[str], None] = "be8edcbbc16f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
